// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetExitInfo() {
  return window['go']['main']['App']['GetExitInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTraffic() {
  return window['go']['main']['App']['GetTraffic']();
}

export function ImportFromText(arg1) {
  return window['go']['main']['App']['ImportFromText'](arg1);
}

export function RemoveNode(arg1) {
  return window['go']['main']['App']['RemoveNode'](arg1);
}

export function RenameNode(arg1, arg2) {
  return window['go']['main']['App']['RenameNode'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function TestLatency(arg1) {
  return window['go']['main']['App']['TestLatency'](arg1);
}