// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nodestore} from '../models';
import {main} from '../models';

export function AddNode(arg1:string):Promise<nodestore.Node>;

export function ClearLogs():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetExitInfo():Promise<main.ExitInfoDTO>;

export function GetLogs():Promise<Array<string>>;

export function GetNodes():Promise<Array<nodestore.Node>>;

export function GetSettings():Promise<nodestore.Settings>;

export function GetStatus():Promise<main.StatusDTO>;

export function GetTraffic():Promise<main.TrafficDTO>;

export function ImportFromText(arg1:string):Promise<number>;

export function RemoveNode(arg1:string):Promise<void>;

export function RenameNode(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:nodestore.Settings):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function TestLatency(arg1:string):Promise<number>;